vich_uploader:
    db_driver: orm

    mappings:
       articles_images:
           uri_prefix: /images/articles
           upload_destination: '%kernel.project_dir%/public/images/articles'
           namer: Vich\UploaderBundle\Naming\UniqidNamer
        #    permet de donner un nom unique aux fichiers uploadés
